services:
  apache:
    build:
      context: .
    container_name: studioclipagem
    restart: always
    platform: linux/arm64
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=studioclipagem.localhost
    networks:
      - network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: studioclipagem-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network
networks:
  network:
    driver: bridge


